name: Download Resume

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Resume HTML
        run: curl -o resume.html 'https://docs.google.com/document/d/1RzkqCB2S9OWcQlwqs7co3hPQLxMg8-lfcqiUtrLNHUI/export?format=html'
      - name: Push Resume
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git diff
          git add .
          git commit -m "Auto-updating resume"
          git push